import type { Metadata } from "next";
import { CssBaseline } from "@mui/material";
import ReduxProvider from "./providers/ReduxProvider";
import ThemeProviderContext from "./providers/ThemeProviderContext";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <ThemeProviderContext>
            <CssBaseline />
            {children}
          </ThemeProviderContext>
        </ReduxProvider>
      </body>
    </html>
  );
}
